name: '@internal/lorem-ipsum'
version: 1.0.0
main: build/index.js
# license, none for the example
license: UNLICENSED
private: true
# scripts comment
scripts:
  build: tsc
  test: jest
  dev: ts-node ./src/index.ts

# plugin stuff
yarn.build:
  input: .
  output: dist
dependencies:
  '@internal/phrase-lorem-ipsum': 'workspace:*'
  lodash: ^4.17.21
  yawn-yaml: ^1.5.0
  typescript: "^4"
  jest: "^26"
  ts-jest: "^26.4.4"

jest:
  preset: ts-jest
devDependencies:
  '@types/node': ^16.4.1
  ts-node: ^10.1.0
  '@types/jest': ^26.0.24
