plugins:
  - path: .yarn/plugins/@ojkelly/plugin-package-yaml.cjs
    spec: "https://yarn.build/yaml"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
