enableGlobalCache: false

packageExtensions:
  "@cspotcode/source-map-support@*":
    dependencies:
      source-map-support: "*"
  "@jest/core@*":
    dependencies:
      ts-node: "*"

plugins:
#   - path: .yarn/plugins/@ojkelly/plugin-package-yaml.cjs
#     spec: "https://yarn.build/yaml"
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"
