on: [pull_request]

name: Build and Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Check dependencies
        run: |
          yarn install --immutable --immutable-cache

      - name: Prettier
        # run yarn style:fix if your PR fails here
        run: |
          yarn style:check

      - name: Build
        run: |
          yarn build

      # Tests are currently broken due to jest/ts/esm issues
      # - name: Test
      #   run: |
      #     yarn test --ignore-cache

      - uses: actions/upload-artifact@v4
        with:
          name: plugins-all
          path: .yarn/plugins/@ojkelly

  integration-test:
    name: Integration Test
    needs: [build]
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        node: [20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"


      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugins-all
          path: e2e/lambda-project/.yarn/plugins/@ojkelly
      - name: Install packages
        run: yarn install --immutable --immutable-cache
      - name: Build plugin
        run: yarn integration:build
      - name: Run integration tests
        run: cd e2e/lambda-project && yarn install --immutable --immutable-cache && yarn run integration
