on:
  push:
    branches:
      - main

name: Latest Release Workflow

jobs:
  build:
    name: Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Build project
        run: |
          yarn install --immutable-cache --check-cache && \
          yarn build && \
          yarn build -c build:update

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            .yarn/plugins/@yarn.build/*
